### PR TITLE
Support of the session engine with Redis 

### PR DESCRIPTION
**Pull request by khaledk2**
This PR adds the support of the session engine with Redis for the Omero  web role
It includes an example of deploying the web client with the Redis session engine in the readme file.

### CODE REVIEW

**Comment by sbesson** [comment]
In general big :+1: for adding Redis to the example. See also #43 for a possible alternative approach using`omero-web[redis]` 

What puzzles me though is that the IDR deployment playbook seems to install `django-redis` without any extra task. So far  I cannot find where the installation happens

**Comment by pwalczysko** [comment]
> where the installation happens

We have a specific redis role, so maybe that is how ? At least this is how (via the role) I install redis in the learning playbook.

**Comment by joshmoore** [comment]
> So far I cannot find where the installation happens

https://github.com/IDR/deployment/blob/825c70b6b778e76d9efbee0aea492d967c0f3753/ansible/idr-omero-web.yml#L7 ?

**Comment by sbesson** [comment]
> We have a specific redis role, so maybe that is how ? At least this is how (via the role) I install redis in the learning playbook.

The `ome.redis` role installs the Redis server but that's not sufficient to install the Redis backend for Django sessions.

After a bit of searching, I think I identified how the installation of `django-redis` happens: `omero-mapr` depends on `omero-web[redis]>=5.14.0` which will install `django-redis` - https://github.com/ome/omero-mapr/blob/9631b155c44fcec9986b03315dd9f5c5c64aa7eb/requirements.txt#L2.
That's very fragile at best, I completely support bringing this installation at the level of the role, possibly using an variable if we want to make optional.

**Comment by pwalczysko** [comment]
> The `ome.redis` role installs the Redis server but that's not sufficient to install the Redis backend for Django sessions.
> 
> After a bit of searching, I think I identified how the installation of `django-redis` happens: `omero-mapr` depends on `omero-web[redis]>=5.14.0` which will install `django-redis` - https://github.com/ome/omero-mapr/blob/9631b155c44fcec9986b03315dd9f5c5c64aa7eb/requirements.txt#L2. That's very fragile at best, I completely support bringing this installation at the level of the role, possibly using an variable if we want to make optional.

Understood and makes sense, thanks for explanation.

**Comment by jburel** [comment]
@pwalczysko that will make sense especially we want to decommission mapr

**Comment by khaledk2** [comment]
I have added a variable to control adding the support of the `Redis `session engine, i.e. `omero_web_setup_redis_session`. The variable default is `false`, so you may not change any of the current installation ansible-playbooks which install the package. 
What do you think?

**Review by sbesson — APPROVED** [review]
I can definitely see how to consume these changes in the IDR deployment playbooks. I'll leave @pwalczysko and @jburel  to comment on the UoD deployment side.

**Review by jburel — APPROVED** [review]
Proposing to merge and tag as 5.1.0
Any objections @pwalczysko?

**Review by pwalczysko — APPROVED** [review]

**Pull request merged**
