### PR TITLE
Move to Ubuntu 2204 and Rocky Linux 9

### PR DESCRIPTION
**Pull request by glyg**
This is not passing tests for the moment, and is trickier than the previous ones

I simplified `molecule.yml` for now, mostly because I don't understand the need for some of the options. 

- Ubuntu with systemd image fails with a write error to `.ansible/tmp` (though the option 
setting tmpfs does not seem to change anything). 

- With the official `ubuntu:22.04` image, the `ome.nginx` role fails due to a gnupg dependency because the role uses a PPA repository to install nginx, any reason not to use the official deb package?

### CODE REVIEW

**Comment by glyg** [comment]
There is kind of the same issue for Ubunutu 22.04 and Rockylinux 9, as both try to install nginx from the `ome.nginx` role, which uses version specific archives (or ppa in the case of Ubuntu).

Should I:
- first fix ome.nginx and then proceed to port this role, or
- "include" a fixed `ome.nginx` role here?

During a meeting @sbesson mentioned building a Galaxy collection for all the role repos, under a unique GH repository, I can see how this would help in this instance :)

**Comment by sbesson** [comment]
> During a meeting @sbesson mentioned building a Galaxy collection for all the role repos, under a unique GH repository, I can see how this would help in this instance :)

More specifically, adding a few links
- https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html 
- https://docs.ansible.com/ansible/latest/dev_guide/developing_collections_structure.html
- https://docs.ansible.com/ansible/latest/dev_guide/migrating_roles.html

In the context of a cohesive body of work like this platform upgrade, it feels like a monolithic structure like a collection would have advantages in terms of distribution & testing. That being said, I would not expect a collection will magically address all problems and the decision to change framework should not be taken lightly.

**Comment by jburel** [comment]
Discussed during last week weekly catch-up, @pwalczysko and @khaledk2 looked at collections and this will introduce more work than required at this stage

**Comment by pwalczysko** [comment]
> Should I:
> 
>     * first fix ome.nginx and then proceed to port this role, or
> 
>     * "include" a fixed `ome.nginx` role here?

@glyg To answer specifically your question, we went in https://github.com/ome/ansible-role-omero-server/pull/69 for the former, see the logic inside the [requirements.yml](https://github.com/ome/ansible-role-omero-server/pull/69/files#diff-be02848eedc97c7cc8d292cde6a8393332cab29ea0aed0587185ed1d3132c31b).

**Comment by glyg** [comment]
all right, thanks for the solution, trying it out quickly :)

**Comment by pwalczysko** [comment]
> all right, thanks for the solution, trying it out quickly :)

Using https://github.com/ome/ansible-role-omero-web/pull/48 and the PRs opened in particular roles repos on which this role is dependent by @glyg and others, we now have OMERO.web running on a RHEL 9 VM. Thanks a lot !

**Comment by glyg** [comment]
Closing as #48 does the job :)

**Pull request closed without merging**
