### PR TITLE
Use new config globbing feature, add tests

### PR DESCRIPTION
**Pull request by manics**
Uses https://github.com/ome/omero-py/pull/137

Rest of the commits rearrange the test files, and adds a py2 → py3 OMERO.web upgrade test.

### CODE REVIEW

**Comment by joshmoore** [comment]
Changes all make sense. Other than the molecule tests, is there a target playbook at the moment? 

As for release, I assume this is part of the next milestone. 2.1.0? 3.0.0?

**Comment by manics** [comment]
`2.1.0` if Python 3 isn't the default, `3.0.0` if it is.

**Comment by joshmoore** [comment]
And which do you suggest?

**Comment by manics** [comment]
`2.1.0` now and advertise to the community they can test a Python 3 deployment by setting a var?

**Comment by manics** [comment]
No targets yet. We don't have any servers we can test this single change on, they'll all need web-apps to be bumped too.

**Comment by joshmoore** [comment]
I'm not sure I follow. You mean there are other PRs needed before we're ready? Can you spell out what those would be and a timeline?

**Comment by manics** [comment]
I meant you can't just bump the role version in requirements, set the python3 variable in a prod-playbook, and expect it to work. You'll also need to update other versions in the playbook, and potentially change some dependencies for the apps.

**Comment by joshmoore** [comment]
Leave you to get this out, but we're still going to need an initial roll-out plan quite soon.

**Comment by manics** [comment]
I think we should treat the 5.6 release like any other major release and not make special allowance for it involving a Python migration. We should be able to methodically work through a playbook, bumping versions as we normally would, ... and see what bugs there are in ansible or OMERO.

Presumably we want a test server for release upgrade testing? So, let's pick one that everyone on the team is prepared to use for testing.

**Comment by joshmoore** [comment]
That sounds great. I'll leave you to have a plan for the systems to test on and the remaining PRs that are needed. The only addition I'll add is that at least from the point-of-view of the dockers there were a number of breaking changes, so I would plan that into the roll-out even if we ultimately don't need the extra time.

**Comment by manics** [comment]
My aim with these latest docker PRs is to get the production containers matching the VMs created by the ansible roles.

**Pull request merged**
